### ISSUE TITLE
PDF file generator does not support formula

### ISSUE THREAD

**Issue by ujos** [burlachenkok/CPP_from_1998_to_2020#11]
It seems the PDF generator does not support formula. It does not convert ` $[-2^{n-1}, 2^{n-1}-1]` into image:

Following is a screenshot:
![image](https://user-images.githubusercontent.com/70940/188427736-f5076396-8ac9-4216-91ae-feceffcb769b.png)

Following is how GitHub interprets the formula:
![image](https://user-images.githubusercontent.com/70940/188428062-f31c918c-e351-4034-beee-40094d545e80.png)

**Comment by burlachenkok** [comment]
Thanks. Fixed.

**Comment by ujos** [comment]
The content in the MD file was right. I'd say it was even better than it is now as formula was embed into the text as a text - not an image. Now, once you added two dollar signs, it is rendered as image on the GitHub.

![image](https://user-images.githubusercontent.com/70940/188449853-31ebdeaa-dc6c-41ee-a77a-e86a485dfedc.png)

I believe what is needed in this ticket is to configure PDF generator to support `mathjax`.

**Comment by burlachenkok** [comment]
Thanks!
I think all has been fixed in generated PDF, HTML, etc.

The software that I'm using to compile Markdown is https://typora.io/

It supports exporting to PDF, HTML, etc.
I have turned on inline math support and it helped. https://support.typora.io/Math/
