### ISSUE TITLE
In C and C++, the components of the variable of structure type struct has addressed

### ISSUE THREAD

**Issue by ujos** [burlachenkok/CPP_from_1998_to_2020#12]
There is following line:

```md
In C and C++, the components of the variable of structure type struct has addressed
```

I'm not really good in English, but looks like there are a few errors:

1. The components ... haVE, as "components" is plural
2. I'm not sure I understand what does it mean "components has(ve) addressed"

**Comment by burlachenkok** [comment]
Rephrased.

**Comment by burlachenkok** [comment]
Please reopen, if the description is still not clean enough.

**Comment by ujos** [comment]
> as in the description in the structure

... in order as they are listed in the structure ?

**Comment by burlachenkok** [comment]
Thanks, updated.
Please keep noticing about any inconsistency.
