### ISSUE TITLE
Each value is implicitly converted to an RValue.

### ISSUE THREAD

**Issue by ujos** [burlachenkok/CPP_from_1998_to_2020#2]
In the Glossary in the description of the `LValue` there is a statement:

> Each value is implicitly converted to an RValue.

What do you mean by this?

**Comment by burlachenkok** [comment]
I prefer just remove that text. Probably I meant that each literal value is rvalue, but it's in fact incorrect.

> 5.1 Literals [expr.prim.literal]
> 1 A literal is a primary expression. The type of a literal is determined based on its form as specified in 5.13. A
> string-literal is an lvalue, a user-defined-literal has the same value category as the corresponding operator call
> expression described in 5.13.8, and any other literal is a prvalue

(https://open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4861.pdf, p.95)
