### ISSUE TITLE
C++ is the fastest general-purpose programming language in the world

### ISSUE THREAD

**Issue by ujos** [burlachenkok/CPP_from_1998_to_2020#3]
In the Introduction there is a statement:

> C++ is complex, but currently, it's the fastest (in terms of execution speed in CPU) high-level, general-purpose programming language in the world.

You need a prove here. Otherwise would be better to reword it into "C++ is one of the most fastest ...."

**Comment by ujos** [comment]
BTW, there is a website where developers are fighting to prove that their programming language is the fastest:

https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html

**Comment by burlachenkok** [comment]
@ujos I saw that web-site, but I did not investigate it too much. Thanks for reference.

For now I prefer to elaborate more. For some reasons I heard that people pickup the simplest language (Python) learn it and do their prototypes....

But you're right - I will try to be more argumentable. Thanks.

**Comment by burlachenkok** [comment]
I have elobarated a bit more.
