### ISSUE TITLE
"The Compiler and Linker. Details." format

### ISSUE THREAD

**Issue by ujos** [burlachenkok/CPP_from_1998_to_2020#5]
Just wonder why is whole chapter formatted as a quote?

**Comment by burlachenkok** [comment]
My original motivation was to put some optional materials (toolchains/asm type things e.g. not directly about C++) to highlight it for easy skip...

**Comment by burlachenkok** [comment]
Please let me know, if you think it's less readable.

**Comment by burlachenkok** [comment]
The "...Details" subsection is big enough, so I have decided to make it as usual text.
