### ISSUE TITLE
Extra parentheses inside the decltype expression

### ISSUE THREAD

**Issue by ujos** [burlachenkok/CPP_from_1998_to_2020#7]
I'm not sure if the following is right:

> ```cpp
> int x;
> const int *p;
> decltype(x) x1;     // x1: int
> decltype(ptr) p1;   // p1: int*
> decltype((ptr)) p2; // p1: const int*
> ```
> 
> Extra parentheses are used to preserve const property for the type of expression.

Tried to compile that code and it seems `decltype(ptr) p1` is equivalent to `const int *p`, so you cannot modify the value pointed by pointer. And `decltype((ptr)) p2` is an equivalent to `const int * &p`.

BTW, there is a typo. There is no `ptr` identifier. Do you mean `p` ?

**Comment by burlachenkok** [comment]
Thanks for pointing out that. I have added examples with class member access and playing with variables to demonstrate difference between `const int *` and `const int *&`.

**Comment by burlachenkok** [comment]
In case of problems - feel free to reopen the issue. Thanks.
